/*
 * This Java source file was generated by the Gradle 'init' task.
 */

package assignmenttwo;

import assignmenttwo.refactoredsolitares.HeavenlyBody;
import assignmenttwo.solarsystem.Star;
import assignmenttwo.solitares.Moon;
import assignmenttwo.solitares.Planet;
import java.lang.reflect.Array;
import java.util.ArrayList;
import java.util.Arrays;

/**
 * This is the generated Hello World Greeting App.
 */
public class App {

  private void sunPlanetMoon() {
    System.out.println("-----Task 1-----");
    System.out.println("Solar System:");
    assignmenttwo.solitares.Star sun = new assignmenttwo.solitares.Star("Sun", 696342);
    System.out.println(" " + sun);

    System.out.println("\nPlanets:");

    assignmenttwo.solitares.Planet[] planets = new assignmenttwo.solitares.Planet[8];
    planets[0] = new assignmenttwo.solitares.Planet("Mrcury", 2439);
    planets[1] = new assignmenttwo.solitares.Planet("Venus", 6051);
    planets[2] = new assignmenttwo.solitares.Planet("Earth", 6371);
    planets[3] = new assignmenttwo.solitares.Planet("Mars", 3389);
    planets[4] = new assignmenttwo.solitares.Planet("Jupiter", 69911);
    planets[5] = new assignmenttwo.solitares.Planet("Saturn", 58232);
    planets[6] = new assignmenttwo.solitares.Planet("Uranus", 25362);
    planets[7] = new assignmenttwo.solitares.Planet("Neptune", 24622);
    for (Planet p : planets) {
      System.out.println(p.toString());
    }

    System.out.println("\n Some moons:");
    assignmenttwo.solitares.Moon[] moons = new assignmenttwo.solitares.Moon[12];
    moons[0] = new assignmenttwo.solitares.Moon("Moon", 1737);
    moons[1] = new assignmenttwo.solitares.Moon("Phobos", 12);
    moons[2] = new assignmenttwo.solitares.Moon("Io", 1821);
    moons[3] = new assignmenttwo.solitares.Moon("Europa", 1560);
    moons[4] = new assignmenttwo.solitares.Moon("Ganymede", 2634);
    moons[5] = new assignmenttwo.solitares.Moon("Callisto", 2634);
    moons[6] = new assignmenttwo.solitares.Moon("Mimas", 2634);
    moons[7] = new assignmenttwo.solitares.Moon("Enceladus", 2634);
    moons[8] = new assignmenttwo.solitares.Moon("Tethys", 2634);
    moons[9] = new assignmenttwo.solitares.Moon("Dione", 2634);
    moons[10] = new assignmenttwo.solitares.Moon("Rhea", 2634);
    moons[11] = new assignmenttwo.solitares.Moon("Titan", 2634);
    for (Moon moon : moons) {
      System.out.println(moon.toString());
    }

  }

  private void heavenlyBody() {
    System.out.println("\n-----Task 2-----");
    System.out.println("Solar System:");
    assignmenttwo.refactoredsolitares.HeavenlyBody sun = new assignmenttwo.refactoredsolitares.Star("sun", 696342);
    System.out.println(" " + sun.toString());

    System.out.println("\nPlanets:");
    assignmenttwo.refactoredsolitares.HeavenlyBody[] planets = new assignmenttwo.refactoredsolitares.Planet[8];
    planets[0] = new assignmenttwo.refactoredsolitares.Planet("Mrcury", 2439);
    planets[1] = new assignmenttwo.refactoredsolitares.Planet("Venus", 6051);
    planets[2] = new assignmenttwo.refactoredsolitares.Planet("Earth", 6371);
    planets[3] = new assignmenttwo.refactoredsolitares.Planet("Mars", 3389);
    planets[4] = new assignmenttwo.refactoredsolitares.Planet("Jupiter", 69911);
    planets[5] = new assignmenttwo.refactoredsolitares.Planet("Saturn", 58232);
    planets[6] = new assignmenttwo.refactoredsolitares.Planet("Uranus", 25362);
    planets[7] = new assignmenttwo.refactoredsolitares.Planet("Neptune", 24622);
    for (HeavenlyBody p : planets) {
      System.out.println(p.toString());
    }

    System.out.println("\n Some moons:");
    assignmenttwo.refactoredsolitares.HeavenlyBody[] moons = new assignmenttwo.refactoredsolitares.Moon[12];
    moons[0] = new assignmenttwo.refactoredsolitares.Moon("Moon", 1737);
    moons[1] = new assignmenttwo.refactoredsolitares.Moon("Phobos", 12);
    moons[2] = new assignmenttwo.refactoredsolitares.Moon("Io", 1821);
    moons[3] = new assignmenttwo.refactoredsolitares.Moon("Europa", 1560);
    moons[4] = new assignmenttwo.refactoredsolitares.Moon("Ganymede", 2634);
    moons[5] = new assignmenttwo.refactoredsolitares.Moon("Callisto", 2634);
    moons[6] = new assignmenttwo.refactoredsolitares.Moon("Mimas", 2634);
    moons[7] = new assignmenttwo.refactoredsolitares.Moon("Enceladus", 2634);
    moons[8] = new assignmenttwo.refactoredsolitares.Moon("Tethys", 2634);
    moons[9] = new assignmenttwo.refactoredsolitares.Moon("Dione", 2634);
    moons[10] = new assignmenttwo.refactoredsolitares.Moon("Rhea", 2634);
    moons[11] = new assignmenttwo.refactoredsolitares.Moon("Titan", 2634);
    for (HeavenlyBody moon : moons) {
      System.out.println(moon.toString());
    }
  }

  private void solarSytem() {
    System.out.println("\n-----Task 3-----");
    assignmenttwo.solarsystem.Star sun = new assignmenttwo.solarsystem.Star("Sun", 696342);

    assignmenttwo.solarsystem.Planet earth = sun.addPlanet("earth", 6371, 63710);
    earth.addMoon("moon", 1737, 17370);

    assignmenttwo.solarsystem.Planet jupiter = sun.addPlanet("jupiter", 69911, 699110);
    jupiter.addMoon("io", 1821, 18210);
    jupiter.addMoon("europa", 1560, 15600);
    jupiter.addMoon("ganymede", 2643, 26340);
    jupiter.addMoon("callisto", 2410, 24100);

    assignmenttwo.solarsystem.Planet mars = sun.addPlanet("mars", 3389, 33890);
    mars.addMoon("phobos", 12, 120);
    mars.addMoon("deimos", 6, 60);

    assignmenttwo.solarsystem.Planet saturn = sun.addPlanet("saturn", 58232, 582320);
    saturn.addMoon("mimas", 198, 1980);
    saturn.addMoon("enceladus", 252, 2520);
    saturn.addMoon("tethys", 533, 5330);
    saturn.addMoon("dione", 561, 5610);
    saturn.addMoon("rhea", 764, 7640);
    saturn.addMoon("titan", 2575, 25750);

    System.out.println(sun);

  }

  private void orderInHeaven() {
    assignmenttwo.solarsystem.Star sun = new assignmenttwo.solarsystem.Star("Sun", 696342);

    assignmenttwo.solarsystem.Planet earth = sun.addPlanet("earth", 6371, 63710);
    earth.addMoon("moon", 1737, 17370);
    assignmenttwo.solarsystem.Planet jupiter = sun.addPlanet("jupiter", 69911, 699110);
    jupiter.addMoon("io", 1821, 18210);
    jupiter.addMoon("europa", 1560, 15600);
    jupiter.addMoon("ganymede", 2643, 26340);
    jupiter.addMoon("callisto", 2410, 24100);

    assignmenttwo.solarsystem.Planet mars = sun.addPlanet("mars", 3389, 33890);
    mars.addMoon("phobos", 12, 120);
    mars.addMoon("deimos", 6, 60);

    assignmenttwo.solarsystem.Planet saturn = sun.addPlanet("saturn", 58232, 582320);
    saturn.addMoon("mimas", 198, 1980);
    saturn.addMoon("enceladus", 252, 2520);
    saturn.addMoon("tethys", 533, 5330);
    saturn.addMoon("dione", 561, 5610);
    saturn.addMoon("rhea", 764, 7640);
    saturn.addMoon("titan", 2575, 25750);
    
    assignmenttwo.solarsystem.HeavenlyBody[] orderInHeaven = sun.getHeavenlyBodies();
    Arrays.sort(orderInHeaven);
    for (assignmenttwo.solarsystem.HeavenlyBody h : orderInHeaven) {
      System.out.println("Heavenly Body: " + h.getName() + ", average radius " + h.getAvgRadiusInKm() + "km");
    }

  }

  /**
   * The App starting point.
   *
   * @param args Unused program arguments.
   */
  public static void main(String[] args) {
    App theApp = new App();
    theApp.sunPlanetMoon();
    theApp.heavenlyBody();
    theApp.solarSytem();
    theApp.orderInHeaven();
  }
}
