/*
 * This Java source file was generated by the Gradle 'init' task.
 */

package assignment4;

import java.io.IOException;

/**
 * This is the generated Hello World Greeting App.
 */
public class App {

  /**
   * Returns a nice greeting message.
   *
   * @return the greeing message.
   */
  public String getGreeting() {
    return "Hello World!!";
  }

  /**
   * The App starting point.
   *
   * @param args Unused program arguments.
   * @throws Exception exception.
   */
  public static void main(String[] args) throws Exception {
    // App theApp = new App();
    // System.out.println(theApp.getGreeting());
    User user = new User();
    user.startMenu();
  }
}
