/*
 * This Java source file was generated by the Gradle 'init' task.
 */

package assignmentone;

import java.util.Arrays;
import java.util.Scanner;

/**
 * This is the main class for the assignment.
 */
public class App {
  private Scanner input;

  private App(Scanner scannerInput) {
    this.input = scannerInput;
  }

  /**
   * Solution to first task.
   */
  public void helloThere() {
    System.out.println("Task 1:");
    System.out.print("Name, please: ");
    String name = input.nextLine();
    HelloThere hello = new HelloThere();
    System.out.println(hello.hello(name));

  }

  /**
   * Solution for the second task.
   */
  public void seconds() {
    System.out.println("\nTask 2:");
    System.out.print("Enter hours, minutes and seconds: ");
    int hour = input.nextInt();
    int minute = input.nextInt();
    int second = input.nextInt();
    Time time = new Time();
    int total = time.toSeconds(hour, minute, second);
    System.out.println("In only seconds that is:  " + total);
  }

  /**
   * Solution for the third task.
   */
  public void imInaBand() {
    System.out.println("\nTask 3:");
    Album album = new Album("Wish You Were Here", 1975, "Pink Floyd");
    System.out.println(album.getName() + " was released in " + album.getYear() + " by " + album.getArtist());
  }

  /**
   * Solution for the fourth task.
   */
  public void bestAlbumsEver() {
    System.out.println("\nTask 4:");
    AlbumGenerator generator = new AlbumGenerator();
    Album[] albums = generator.generateAlbums();
    for (int i = 0; i < albums.length; i++) {
      System.out.println(albums[i].getName() + " was released in " + albums[i].getYear()
          + " by " + albums[i].getArtist());
    }
  }

  /**
   * Solution for the fifth task.
   */
  public void workingWithArrays() {
    System.out.println("\nTask 5:");
    int[] arrayList = {5, 2, 6, 4, 1, 3, 7, 9, 8 };
    ArrayAlgorithms arr = new ArrayAlgorithms();
    for (int i : arrayList) {
      System.out.print(i + " ");
    }
    System.out.println("\nAverage is: " + arr.average(arrayList));
    System.out.println("Largest value is: " + arr.maxValue(arrayList));
    System.out.println("Index of smallest value is at position: " + arr.minIndex(arrayList));
    System.out.println("Shifted array:\n" + Arrays.toString(arr.shift(arrayList)));
    System.out.println("Shuffled array:\n" + Arrays.toString(arr.shuffle(arrayList)));
  }

  /**
   * Starting point of the first assignment.
   *
   * @param args is not used.
   */
  public static void main(String[] args) {

    // we create a scanner object to work with
    // it is advised to create one and only one scanner for a specific stream in the
    // whole application
    // scanners should be closed when you are done and this also closes the
    // underlying stream
    Scanner consoleInput = new Scanner(System.in, "UTF-8");

    App app = new App(consoleInput);

    // Task 1
    app.helloThere();

    // Task 2
    app.seconds();

    // Task 3
    app.imInaBand();

    // Task 4
    app.bestAlbumsEver();

    // Task 5
    app.workingWithArrays();

    // now we are exiting the application so time to close the scanner.
    consoleInput.close();
  }
}
